const wasteItems = [
  { id:'b1', icon:'🍌', name:'Banana Peel', cat:'bio', catLabel:'Biodegradable',
    desc:'Fruit peels are organic matter that breaks down naturally through composting or in soil.',
    steps:['Remove any stickers or non-organic tags','Drop directly into the green biodegradable bin','Alternatively, add to your home compost heap','Avoid leaving loose on ground to prevent pests'],
    bin:'🟢 Green Bin — Compost/Biogas' },
  { id:'b2', icon:'🌿', name:'Garden Clippings', cat:'bio', catLabel:'Biodegradable',
    desc:'Grass, leaves, and plant trimmings are excellent composting materials that enrich soil.',
    steps:['Collect in a bag or bin','Avoid mixing with diseased plants','Place in green bin or compost pile','Can also be mulched in place'],
    bin:'🟢 Green Bin — Compost/Biogas' },
  { id:'b3', icon:'🥚', name:'Eggshells', cat:'bio', catLabel:'Biodegradable',
    desc:'Eggshells break down over time and add calcium to compost, benefiting soil and plants.',
    steps:['Rinse eggshells to remove egg residue','Let dry briefly if possible','Crush to speed up decomposition','Add to compost or green bin'],
    bin:'🟢 Green Bin — Compost/Biogas' },
  { id:'b4', icon:'🍵', name:'Tea Bags', cat:'bio', catLabel:'Biodegradable',
    desc:'Most tea bags and their contents are compostable. Check if the bag is plastic-free first.',
    steps:['Check if bag is plastic-free or mesh','Paper tea bags go directly to compost','Plastic-mesh bags: empty tea leaves into compost, bin the bag','Coffee grounds work the same way'],
    bin:'🟢 Green Bin — Compost/Biogas' },
  { id:'b5', icon:'🍖', name:'Food Scraps', cat:'bio', catLabel:'Biodegradable',
    desc:'Most food waste can be composted and turned into nutrient-rich material for soil.',
    steps:['Scrape food into a compost-safe bag or container','Meat and dairy should go to council green bins only','Plant-based scraps can go in home compost','Seal well to avoid odors and pests'],
    bin:'🟢 Green Bin — Compost/Biogas' },
  { id:'b6', icon:'📰', name:'Newspaper', cat:'bio', catLabel:'Biodegradable',
    desc:'Plain newsprint is biodegradable and also great as a composting layer between food scraps.',
    steps:['Separate from coated or glossy paper','Can be shredded and used in compost','Acts as a carbon layer between food scraps','Or place in recycling bin if clean'],
    bin:'🟢 Green Bin or 🔵 Recycling' },
  { id:'r1', icon:'🍶', name:'Glass Bottle', cat:'rec', catLabel:'Recyclable',
    desc:'Glass is 100% recyclable and can be recycled indefinitely without losing quality.',
    steps:['Rinse to remove food residue','Remove caps and corks (recycle separately)','Do not break — whole bottles are easier to process','Place in blue recycling bin'],
    bin:'🔵 Blue Bin — Glass Recycling' },
  { id:'r2', icon:'📦', name:'Cardboard Box', cat:'rec', catLabel:'Recyclable',
    desc:'Cardboard is widely recycled and can be turned into new paper products and packaging.',
    steps:['Remove all tape, staples, and plastic inserts','Flatten the box to save space','Keep dry — wet cardboard cannot be recycled','Place in blue recycling bin'],
    bin:'🔵 Blue Bin — Paper Recycling' },
  { id:'r3', icon:'🥤', name:'Plastic Bottle', cat:'rec', catLabel:'Recyclable',
    desc:'PET plastic bottles (marked with recycling symbol #1) are among the most recycled plastics.',
    steps:['Empty and rinse the bottle','Crush or compress to save space','Leave the cap on (many facilities can now recycle them)','Check the recycling number on the bottom'],
    bin:'🔵 Blue Bin — Plastic Recycling' },
  { id:'r4', icon:'🥫', name:'Metal Can', cat:'rec', catLabel:'Recyclable',
    desc:'Aluminium and steel cans are highly recyclable with a fraction of the energy of new production.',
    steps:['Rinse to remove food or liquid','You can crush it to save space','Remove paper labels if they come off easily','Place in blue recycling bin'],
    bin:'🔵 Blue Bin — Metal Recycling' },
  { id:'r5', icon:'💻', name:'Old Laptop', cat:'rec', catLabel:'Recyclable',
    desc:'Electronics contain valuable metals and hazardous components — they need e-waste recycling.',
    steps:['Wipe all personal data before disposal','Do NOT put in regular bins','Take to an e-waste collection facility or store','Many manufacturers offer take-back programs'],
    bin:'🔵 E-Waste Drop-off Point' },
  { id:'r6', icon:'👕', name:'Old Clothes', cat:'rec', catLabel:'Recyclable',
    desc:'Textiles can be donated, resold, or sent to textile recycling to be made into new fibre.',
    steps:['Wash clothing before donating','Donate wearable items to charity shops','Torn items can go to textile recycling bins','Never mix with household waste'],
    bin:'🔵 Textile Recycling Point' },
  { id:'h1', icon:'🔋', name:'AA Battery', cat:'haz', catLabel:'Hazardous',
    desc:'Batteries contain toxic heavy metals like mercury, cadmium, and lead that can leach into soil and water.',
    steps:['Never throw in regular household waste','Store used batteries in a sealed container','Take to a battery recycling drop-off point','Many supermarkets and hardware stores offer this'],
    bin:'🔴 Hazardous — Battery Drop-off' },
  { id:'h2', icon:'💊', name:'Old Medicine', cat:'haz', catLabel:'Hazardous',
    desc:'Medicines flushed or binned can contaminate water systems and harm wildlife and ecosystems.',
    steps:['Do NOT flush down the toilet','Do NOT throw in household bin','Return to any pharmacy for safe disposal','Keep in original packaging where possible'],
    bin:'🔴 Hazardous — Pharmacy Return' },
  { id:'h3', icon:'🖌️', name:'Paint Can', cat:'haz', catLabel:'Hazardous',
    desc:'Liquid paint contains solvents and pigments that are toxic to soil and waterways.',
    steps:['Let leftover paint dry out completely if small amount','Take liquid paint to a hazardous waste facility','Some facilities accept paint for community reuse','Label the container clearly before drop-off'],
    bin:'🔴 Hazardous Waste Facility' },
  { id:'h4', icon:'🧪', name:'Chemical Cleaner', cat:'haz', catLabel:'Hazardous',
    desc:'Household chemicals like bleach, drain cleaner, and solvents require careful safe disposal.',
    steps:['Keep in original labeled containers','Never mix different chemicals','Do NOT pour down drains or into soil','Take to council hazardous waste collection day'],
    bin:'🔴 Hazardous Waste Facility' },
  { id:'h5', icon:'💡', name:'CFL Bulb', cat:'haz', catLabel:'Hazardous',
    desc:'Compact fluorescent lamps contain mercury and must not go into regular bins or be shattered.',
    steps:['Handle carefully — do not break','Place in a sealed bag for transport','Take to lighting retailer or council facility','LED bulbs are safer but still need e-waste disposal'],
    bin:'🔴 Hazardous — CFL Drop-off' },
  { id:'h6', icon:'🩸', name:'Medical Sharps', cat:'haz', catLabel:'Hazardous',
    desc:'Needles and syringes are a puncture and infection risk. They must be stored in sharps containers.',
    steps:['Place used sharps immediately into a sharps container','Do NOT recap needles','Return full sharps container to a pharmacy or hospital','Never put in household bins or recycling'],
    bin:'🔴 Hazardous — Sharps Container' },
];

const quizQuestions = [
  { emoji:'🍌', hint:'Banana peel',         answer:'bio', explain:'Banana peels are organic matter that naturally decomposes — perfect for composting!' },
  { emoji:'🥤', hint:'Plastic water bottle', answer:'rec', explain:'PET plastic bottles can be recycled into new bottles and clothing fibres.' },
  { emoji:'🔋', hint:'Used battery',         answer:'haz', explain:'Batteries contain toxic metals — take them to designated drop-off points.' },
  { emoji:'📦', hint:'Cardboard box',        answer:'rec', explain:'Flatten and recycle cardboard in the blue bin — it becomes new paper products.' },
  { emoji:'💊', hint:'Expired medicine',     answer:'haz', explain:'Return medicines to a pharmacy. Flushed medicine contaminates water systems.' },
  { emoji:'🥚', hint:'Eggshell',             answer:'bio', explain:'Eggshells are biodegradable and add calcium to compost!' },
  { emoji:'🥫', hint:'Empty tin can',        answer:'rec', explain:'Metal cans are infinitely recyclable! Rinse and pop in the blue bin.' },
  { emoji:'🖌️', hint:'Leftover paint',      answer:'haz', explain:'Liquid paint contains solvents — take it to a hazardous waste facility.' },
];